---
- name: settings for dev instances in AWS
  hosts: all

  tasks:
  - name: Ensure c:\temp exists
    win_file:
      path: c:\temp
      state: directory

  - name: Change the hostname to sample-hostname
    ansible.windows.win_hostname:
      name: RP-DEV-14
    register: res

  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required
