---
- name: settings for all windows servers
  hosts: all

  tasks:
  - name: Ensure c:\temp exists
    win_file:
      path: c:\temp
      state: directory

  - name: Ensure DAC service is running
    win_service:
      name: DAC
      state: started
