---
- name: settings for all windows servers
  hosts: all

  tasks:
  - name: Ensure c:\temp exists
    win_file:
      path: c:\temp
      state: directory
      
  - name: Get info for DAC service
    ansible.windows.win_service_info:
      name: DAC
    register: service_info

  - name: Ensure DAC service is running
    win_service:
      name: DAC
      state: started
